DEFAULT_THUMBNAIL_SIZE = 100  # 100 pixels wide
DEFAULT_PAGE_SIZE = 900  # 900 pixels wide
JPG = "jpg"
PAGES = "pages"
THUMBNAILS = "thumbnails"
DOCVERS = "docvers"
OCR = "ocr"
INDEX_ADD_DOCS = "index_add_docs"
WORKER_OCR_DOCUMENT = "worker_ocr_document"
